/** Paths from specs/init.md «Created files» (excluding conditional `.env`). */
export const INIT_SCAFFOLD_FILES = [
  "package.json",
  "tsconfig.json",
  ".gitignore",
  "aether.config.json",
  ".env.example",
  "src/main.ts",
  "src/app/composition.ts",
  "src/app.ts",
  "src/app/config.ts",
  "src/app/server.ts",
  "src/app/router.ts",
  "src/app/http.ts",
  "src/app/list.ts",
  "src/app/logger.ts",
  "src/app/middleware/types.ts",
  "src/app/middleware/request-logger.ts",
  "src/app/middleware/error-handler.ts",
  "src/app/middleware/cors.ts",
  "src/app/middleware/body-limit.ts",
  "src/app/middleware/bearer-auth.ts",
  "src/health/health.routes.ts",
] as const;
